name: Contributors
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master
permissions: write-all
jobs:
  contributors: Jeranimo25
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          round: true
